### ISSUE TITLE
Redundant modem NV partition dump

### ISSUE THREAD

**Issue by fxsheep** [OpenStick/stick-blobs#1]
Qualcomm's modem NV partitions (i.e. `fsg,fsc,modemst1,modemst2`) are encrypted with an SoC-unique key, and consequently the backup is only valid for the device it's created from. To create a sharable NV backup, a common way is to export it as a QCN/xQCN file via QPST.

**Comment by HandsomeYingyan** [comment]
Thanks for the infomation,QCN files will add shortly.
